### ISSUE TITLE
To-Do for altogether meeting

### ISSUE THREAD

**Issue by PhiSpel** [joergbrech/Modellbildung-und-Simulation#263]
- [x] tidy up issues
- [x] tidy up branches
- [x] agree on naming in gh
